name: tigmv-312
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy=1.26.4
  - scipy=1.11.4
  - matplotlib=3.8.4
  - scikit-image=0.22.0
  - pip
  - pip:
      - bezier==2024.6.20
      - opencv-python==4.9.0.80
      - pillow==10.3.0
      - pydicom==2.4.4
      - tqdm==4.66.4
      - pytest==7.4.4
      - pytest-mpl==0.16
      - black==24.4.2
      - ruff==0.4.8
      - mypy==1.10.0
