name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            requirements-dev.txt
      - run: pip install -e .
      - run: pip install -r requirements-dev.txt
      - run: pre-commit run --all-files
      - run: pytest -q
